# Generated by Django 3.0.6 on 2020-05-07 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('sipIdentifier', models.CharField(max_length=200)),
                ('online', models.BooleanField()),
                ('classe', models.CharField(max_length=255)),
                ('photoUrl', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('messageText', models.TextField(null=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('audio', models.FileField(null=True, upload_to='')),
                ('received', models.BooleanField()),
                ('seen', models.BooleanField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('messageText', models.TextField(null=True)),
                ('video', models.FileField(null=True, upload_to='')),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('audio', models.FileField(null=True, upload_to='')),
                ('groupChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.GroupChat')),
                ('users_rec', models.ManyToManyField(related_name='users_rec', to='main_app.User')),
                ('users_seen', models.ManyToManyField(related_name='users_seen', to='main_app.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='groupchat',
            name='users',
            field=models.ManyToManyField(related_name='users', to='main_app.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('timestamp', models.DateTimeField()),
                ('videoCall', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User')),
            ],
        ),
    ]
